Fixing listen version to 1.0.x.
Listen 2.0.0 was released, and the method Listener#start! was removed.
The new version is throwing the following exception on rerun:
    rerun-0.8.1/lib/rerun/watcher.rb:62:in `block in start':
    undefined method `start!' for #<Listen::Listener:0x007fe764a47ee8>
    (NoMethodError)